# This rule is not used by the project bookapp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the webapp.y2505.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bookapp
    app.kubernetes.io/managed-by: kustomize
  name: bookapp-editor-role
rules:
- apiGroups:
  - webapp.y2505.com
  resources:
  - bookapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.y2505.com
  resources:
  - bookapps/status
  verbs:
  - get
